version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['npm', 'start']
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
